[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#212121"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f57373"
white = "#eeffff"
yellow = "#ffcb6b"

[colors.cursor]
cursor = "#ffcb6b"
text = "#1d1f21"

[colors.normal]
black = "#212121"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f57373"
white = "#eeffff"
yellow = "#ffcb6b"

[colors.primary]
background = "#212121"
foreground = "#eeffff"

[cursor]
unfocused_hollow = false
thickness = 0.4
blink_interval = 500

[cursor.style]
shape = "Beam"
blinking = "Always"

[debug]
persistent_logging = true

[font]
size = 10

[font.bold]
family = "Iosevka NFM"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka NFM"
style = "Italic"

[font.normal]
family = "Iosevka NFM"
style = "Normal"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
dynamic_title = true

[window.padding]
x = 15
y = 10
